version: '3.9'

services:
  app:
    image: webdevops/php-apache:7.4
    volumes:
      - .:/app
    ports:
      - 80:80
    environment:
      - PHP_DISPLAY_ERRORS=1
  db:
    image: mongo:latest
    # uncomment if you want to persist data
    # volumes:
    #   - /change/this/path:/data/db
    ports:
      - 27017:27017
